# Configuration file for Dask ML Pipeline

# Dataset Configuration
dataset:
  name: "california_housing"
  scale_factor: 15  # Reduced to prevent memory issues
  test_size: 0.2
  random_state: 42

# Dask Configuration
dask:
  n_workers: 2  # Reduced from 4 to 2
  threads_per_worker: 2
  memory_limit: "1GB"  # Reduced from 2GB to 1GB
  local_directory: "./dask-worker-space"
  
# Model Configuration
model:
  type: "RandomForestRegressor"  # Changed to more memory-efficient model
  n_estimators: 50  # Reduced from 100
  max_depth: 5  # Reduced from 10
  random_state: 42
  n_jobs: -1

# Training Configuration
training:
  cv_folds: 3  # Reduced from 5
  scoring: "neg_mean_squared_error"
  verbose: True

# Performance Analysis
performance:
  enable_profiling: True
  memory_tracking: True
  timing_analysis: True
  comparison_with_traditional: True

# Visualization
visualization:
  save_plots: True
  plot_format: "png"
  dpi: 300
  interactive: True

# Output Configuration
output:
  models_dir: "results/models"
  plots_dir: "results/plots"
  reports_dir: "results/reports"
  save_model: True
  save_predictions: True 